### ISSUE TITLE
Portable Header File for CPU Features Detection

### ISSUE THREAD

**Issue by RoyiAvital** [steinwurf/cpuid#37]
Hello,

Could you offer a version of `h` file (Even in `C`) for detection of CPU features?
Something which expose simple functions like `hasSSE3()`, `hasSSE4()`, `hasAVX()`, `hasAVX2()`, etc...

Thank You.

**Comment by mortenvp** [comment]
Hi @RoyiAvital are you thinking about a header-only version of the library. Or bindings for the library to expose it's functionality to C?

**Comment by RoyiAvital** [comment]
Either way. But just having the functionality withing the IDE without the need to build a library and link it.

**Comment by mortenvp** [comment]
@RoyiAvital Making the library header only atm. is not easy since we have other dependencies that would then be exposed. Is there some reason you prefer not to use it as a shared/static lib?

**Comment by mortenvp** [comment]
Closing this issue - feel free to (re)open again with new questions.
