### ISSUE TITLE
F16C request.

### ISSUE THREAD

**Issue by Niko40** [steinwurf/cpuid#45]
Hey.
I was looking around for a cross compiler library like this and looks like this is the best so far.

Would it be possible to add a test for F16C extensions? https://en.wikipedia.org/wiki/F16C
EAX == 1, ECX bit 29.

I'm building some Vulkan stuff (libraries) on my free time, and I'm considering using 16 bit floats for HDR textures to save some VRAM. Currently I have a pretty good sulution of converting between the two but I wouldn't mind a speedup on processors that support this.

**Comment by jpihl** [comment]
Hi Niko40,

This feature will soon be available.

Cheers,

Jeppe
